"""Learning-sample filters for command and framework-generated messages."""

from __future__ import annotations

import re
from typing import Any, Iterable, List, Optional


COMMAND_PREFIXES = ("/", "!", "#", ".")
BARE_COMMANDS = {
    "help",
    "new",
    "provider",
    "reset",
    "history",
    "persona",
    "plugin",
    "model",
    "tools",
}

SYSTEM_RESPONSE_PATTERNS = (
    re.compile(r"^AstrBot\s+v?\d", re.IGNORECASE),
    re.compile(r"^/[\w-]+\s+-\s+", re.MULTILINE),
    re.compile(r"^(Traceback|Exception|Error|TimeoutError):", re.IGNORECASE),
    re.compile(
        r"(调用超时|请求超时|发生错误|模型调用失败|Provider\s+.*未配置|timeout)",
        re.IGNORECASE,
    ),
)


def _normalize_text(message_text: Any) -> str:
    return "" if message_text is None else str(message_text).strip()


def is_command_message(message_text: Any) -> bool:
    """Return true for explicit AstrBot command inputs."""
    text = _normalize_text(message_text)
    if not text:
        return False

    first_token = text.split(maxsplit=1)[0].strip()
    normalized = first_token.lower().lstrip("".join(COMMAND_PREFIXES))
    if first_token[:1] in COMMAND_PREFIXES and len(first_token) > 1:
        return bool(first_token[1].isalpha())
    return text.lower() in BARE_COMMANDS or (
        normalized in BARE_COMMANDS and text == first_token
    )


def is_system_response(message_text: Any) -> bool:
    """Return true for framework help/error output that should not be learned."""
    text = _normalize_text(message_text)
    if not text:
        return False

    if any(pattern.search(text) for pattern in SYSTEM_RESPONSE_PATTERNS):
        return True

    help_lines = sum(
        1
        for line in text.splitlines()
        if re.match(r"^/[\w-]+\s+-\s+", line.strip())
    )
    return help_lines >= 2


def should_ignore_learning_sample(
    message_text: Any,
    *,
    sender_id: Optional[str] = None,
    is_bot: bool = False,
) -> bool:
    """Return true when a message is generated by commands or system templates."""
    text = _normalize_text(message_text)
    if not text:
        return True
    if is_bot or str(sender_id or "").lower() == "bot":
        return is_system_response(text)
    return is_command_message(text) or is_system_response(text)


def filter_learning_messages(messages: Iterable[Any]) -> List[Any]:
    """Filter dict/object messages before they are used for learning samples."""
    filtered: List[Any] = []
    for item in messages or []:
        if isinstance(item, dict):
            text = item.get("message", "")
            sender_id = item.get("sender_id")
        else:
            text = getattr(item, "message", "")
            sender_id = getattr(item, "sender_id", None)
        if should_ignore_learning_sample(
            text,
            sender_id=sender_id,
            is_bot=str(sender_id or "").lower() == "bot",
        ):
            continue
        filtered.append(item)
    return filtered
